name: Swift

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        files: .build/debug/codecov/Library.json
        fail_ci_if_error: false
        verbose: true
