name: Swift

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Convert Swift coverage
      uses: sersoft-gmbh/swift-coverage-action@v2
      id: coverage-files
      with:
        format: lcov
        ignore-conversion-failures: true
        fail-on-empty-output: false
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        files: files: ${{join(fromJSON(steps.coverage-files.outputs.files), ',')}}
        fail_ci_if_error: false
        verbose: true
